use_frameworks!

platform :ios, '13.0'
inhibit_all_warnings!

target 'HCPChat_Example' do
  pod 'HCPChat', :path => '../'
  
  pod 'SendBirdUIKit'

  target 'HCPChat_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
    # some older pods don't support some architectures, anything over iOS 11 resolves that
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
